name: CreateOnMinecraft
version: 1.0-SNAPSHOT
main: dev.createonmc.CreateOnMinecraftPlugin
api-version: "26.1.2"
description: Recreating the Create mod as a Paper plugin
author: Demarky

commands:
  ssggive:
    description: Give a Create item
    usage: /ssggive <gear|biggear|eixo|motor [rpm]|water_wheel>
    permission: createonmc.ssggive
  gearstress:
    description: Multiply gear placements in a line for performance testing
    usage: /gearstress <n>
